name: hello workflow
on: push
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "hello, github actions!"
      - name: checkout
        uses: actions/checkout@v6
