name: hello workflow
on: push
jobs:
  say-hello1:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "hello1, github actions!"
      - name: checkout
        uses: actions/checkout@v6
  say-hello2:
    needs: say-hello1
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo "hello2, github actions!"
      - name: checkout
        uses: actions/checkout@v6
