name: hello workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - dev-*
  workflow_dispatch:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: echo '${{ toJSON(github) }}'
